development:
  adapter: postgresql
  database: radiant_dev
  username: yarneo
  password: yarden
  host: localhost

test:
  adapter: postgresql
  database: radiant_test
  username: yarneo
  password: yarden
  host: localhost

production:
  adapter: postgresql
  database: radiant_live
  username: yarneo
  password: yarden
  host: localhost